service: scumbler-spillguard

provider:
  name: aws
  runtime: python3.6
  memorySize: 512
  timeout: 300
  awsKmsKeyArn: arn:aws:kms:us-west-2:521597827845:key/babb304b-1922-4f8d-b93e-2f1a0cd81f3a

functions:
  githubWebhookListener:
    events:
      - http:
          path: github
          method: post
    handler: handler.github
    description: Forwards matching events to Scumblr
    vpc:
      securityGroupIds:
        - sg-f0c1ef8b
      subnetIds:
        - subnet-46b57a31
        - subnet-3dbb1258
        - subnet-237dfa7a
    environment:
      ENCRYPTED_GITHUB_TOKEN: AQICAHjS09yT/3JrgjtoGzEEeXg8F1MQ6FW7O66NS84I7m/nNgE3cmmSohnYxdjqk5Pgcv4KAAAAhzCBhAYJKoZIhvcNAQcGoHcwdQIBADBwBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDLYMUs2iXmrK9QhFXwIBEIBDt5ZnC+ZVTV9O7XBZ3AAh5i0IU1UxGhsI/gu66YPP6qaj9R3LKSRgT+xfzDLuxV9OYQvzB63OB+aC2eFR86SHNuhDHw==
      ENCRYPTED_SCUMBLR_KEY: AQICAHjS09yT/3JrgjtoGzEEeXg8F1MQ6FW7O66NS84I7m/nNgGVACN2BDVO6D0MeQPZZbK6AAAG9jCCBvIGCSqGSIb3DQEHBqCCBuMwggbfAgEAMIIG2AYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAxxT1UDRX8/gTrJcJICARCAggapWnz0T+XCR82umMXud0K2agFCulyUHZHdmRCDmKkT5cXCAnwVbhXb7L8hD8SSJUXlfJ4z+qRULM4Qfu/VlG/UGZlB7b2Ti+tyQbRHDanKNmK9fQlOQweHD5Nu3CngCnXPG/3bhyUeayjEdy5M1u9UxLGZOeATzYKXtNtG/+tBxHwDKNqcqQGkxHu4NXJ7w3On/mFnjLCs2Ct2WU3hDO7fSJqj9jUPOp0dhe6jfzRXVRucJVVLxnYGThp9Tp1ajS2OyvG+CSndYRmueJAjKeRprpNQ5v4vrxNKjKzO6IecXOj5vUheKwy7RAPBl1+gKixWDponV/YZATve0NWTW/sd5LvS4i9N8EUfxmigrVXrEBkO7fwVWiVSuU+frpvi5bMIc5gN+nDn8vZZibN6I00kgqignpYf6jw15J3OCHjWmYRwNK632/91d14OhFTQR5nvNAo28Rr76giF0ZXxgINxLtNsgjc5XMgwL6owEFkSYQiYBqDoHZSCqG01wSTqKIpC4ZrRziOI0GJDyBEK/I0jH1dW2PAj0IcxL0UvApQKWZuzd71llYEcy47A8si2bAMlcy2/N6KiQ4KQmBbNisugb9JIOCknA9+MQDXpqfVHzFSe5wkHOSeuqXihseS8aFa8P92s832CV9M0ez6ILsgeir/lm6KSEQCkoCfcDW6XSPj6DD0IlT9Jni3qAPHStcRy+B6EjlU6MiP0n2iuhYdNBemVkA3NTU6UhJQxwdaT5cbyt90AL+rnFGvS/AqGBdDpPnbVJTb9pmdSnC4V6vA56Qf61OAucF6TnvVbpI3lOK8qut0NszQlv4tkv75x5yLs01v4JnVAht3BgCMTnbWvubz5joZHOmnR6qN/B0X29PoI4VCVcxOMm4PWeFlFryVcQGzsolyZ0AHspWk+cmCmFgP4v1w5HjlxvniB772LJPymTpSZOD73cHp83AtzsgwE/BziHre4qyvdOtvOOgjTsbvoJddlsbUuE76//OAwmnmlWmUl6AhoXqx0uNVXy14pckM/aiihhp8TEMnU9VNsxhMu9srV1kIi0i3WlX7VYHUqwHJJiRYVIOfzfXYaSU5N+Z7FXjJvxOhZdXW1S3MPNA1gIrHSie5hZWsHbVajX16WQQOrfUwhm+KhtabktGrTKIAVZE317KMOzoxUn1fy9GniwgpAYyHZ4NPk/Y9NrTLjZohw22cO3P/cWjAGjhJqTzsOJ4C6fdLSLWls9BPR6H1+pk3IgsXRIH2KgSuzFQLQPHIKKZ0rfLstNXaiZ7VsWFNtmjIl0hkGS6U9t7GoU6G/IFUmi+LsyKm5LNJe6/FzCDwSFTbkHhcE1+hNH3Bv3RmyOqlATwgjIavpmFD/9KIyk9k15Bt1QsQEesW912z0/GiXMoEOoKnfvCjL4IJJJW8sjmq0cHZWOTyBCecYkPSNGVBUP38rzJ/T9aQ5vKcU9HlwDUOBnaG8irPhioJu7smQ2b99l+8+MvaiGpgnU7EkFNntq6AP0RbLtD2wQ+NBGvSeY4tv1kdKG2Z1zglo356hPC6ub55k0BDfuakFBHZg7+xoL3dW4y0mZ9sOapFWNN/5ipkLkicQSmvPmjEtC3RbLXxJl/14jxAQDlJ72piTqomClOlor47H4MsbfZbssTrHkAS4WuIZxPkvVN/cYAdZBu1ov2RSsame6CFWkV1EsGWPEmqb8heR/PC2NEohq1TScfyrx2gjxVRT6lU3zZFFbdF6+HPqwHwaBBzn6QaJSHlc5LlZt9xQeUc5Yh+rkcPDJ6wOc5uad2U7sxqIpLCnS2N08njR/bhJ6vkR+G+q1jxTCt33cWhBw+vxpJtHvjUfNqUTg9seGLbkqQpq2aB7a/ZCbt8NdqfipTcK7+qVKi0z54Iqd0tJzDMvJRoMTCSCOMag1hemV+RJ9TBYyE3bHA1iF+VppnERuLpwbjg1/IS+nZ92Av8Axvj35dSyoXzehTvJPGH/6s8W7YrEF+0lxB2wpT4NDpXf10PxmRkLOCH6J1X/p4XmF0+gSHFoYRkFvggO6z2mGTQl7rr8IqrH26ptIET+i+UfeNB60+v1nKmAM3kOuPI0mGU2ttKug21Y+WGXyo8bnwqidJQAuBdgT8yjR9Jhs39E23dF9pOcOub5WAL0S10pwoGdnf4mxo7eFee5wdLsVdrdRlNfoP6ZDZ8c0oTDWwS+8IQ6XKL6YswSdbGjJzYqujnwooQL5RjP8JqCDVCVZwewxteFybxRl9MmIBN8tzhofc46Zi02TyfRPsvFLA==
      ENCRYPTED_WEBHOOK_SECRET: AQICAHjS09yT/3JrgjtoGzEEeXg8F1MQ6FW7O66NS84I7m/nNgGylu17sMGprxSZB3XrWmIsAAAAhzCBhAYJKoZIhvcNAQcGoHcwdQIBADBwBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDP5TVKhluss12iLJowIBEIBDSKQGA+sa5qL3KBrAJ5RIAIobxLh2W6HKMMxDOmxfMkS74h3FbCfazXLyT+6D/D6PN83VPFW0DJrWMIxG9HyWBWg3nQ==
      SCUMBLR_URL: https://scumblr.mgmttest.netflix.net

plugins:
  - serverless-python-requirements